# Generated by Django 5.1.2 on 2024-10-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="quiz_images/")),
                ("answer", models.CharField(max_length=100)),
                ("hint", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
