# Generated by Django 5.1.2 on 2024-10-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=50)),
                ("score", models.IntegerField(default=0)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-score", "-played_at"],
            },
        ),
    ]
