# Generated by Django 5.1.2 on 2024-10-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_playerscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizimage",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "매우 쉬움"), (2, "쉬움"), (3, "보통"), (4, "어려움"), (5, "매우 어려움")],
                default=1,
            ),
        ),
    ]
