# Generated by Django 5.1.2 on 2024-10-24 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_quizimage_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerscore",
            name="played_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
